print('hello')
print('import antigravity')
print('import __hello__')
print('from __future__ import braces')

print('\nEscape  sequences')
print('\\a-Bell (alert)')
print('\\b-Backspace')
print('\\n-New line')
print('\\t-Horizontal tab')
print('\\\ - Backslash')
print('\\"-Double quotation mark "')
print("\\'- Single quotation mark '")
